# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('V_DSNID', models.CharField(blank=True, default='', max_length=25)),
                ('V_SEGMENT_CODE', models.CharField(blank=True, default='', max_length=10)),
                ('V_SEGMENT_NAME', models.CharField(blank=True, default='', max_length=30)),
                ('V_SEGMENT_DESC', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'SEG_FOLDER',
                'managed': False,
            },
        ),
    ]
