# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170525_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('display_name', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=30, primary_key=True)),
            ],
            options={
                'db_table': 'COLUMNS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsiMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.BigIntegerField()),
                ('sequences', models.BigIntegerField()),
                ('msg_timestamp', models.DateTimeField()),
                ('message_cd', models.IntegerField()),
                ('msg_severity_cd', models.IntegerField(blank=True, null=True)),
                ('batch_run_id', models.CharField(blank=True, max_length=75, null=True)),
                ('context_specific_text', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'fsi_message_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsiMObjectDefinitionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_definition_id', models.BigIntegerField(unique=True)),
                ('object_origin_app_cd', models.CharField(max_length=30)),
                ('leaf_num_id', models.IntegerField()),
                ('id_type', models.SmallIntegerField()),
                ('table_name', models.CharField(max_length=30)),
                ('folder_id', models.BigIntegerField(blank=True, null=True)),
                ('folder_name', models.CharField(blank=True, max_length=30, null=True)),
                ('access_cd', models.CharField(blank=True, max_length=1, null=True)),
                ('appl_name', models.CharField(max_length=10)),
                ('deleted_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('source_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fsi_m_object_definition_b',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsiMObjectDefinitionTl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_definition_id', models.BigIntegerField()),
                ('short_desc', models.CharField(max_length=60)),
                ('long_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('lang_cd', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=30, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('source_lang', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'fsi_m_object_definition_tl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TABLES',
                'managed': False,
            },
        ),
    ]
