# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_BATCH_ID', models.IntegerField(default=0)),
                ('V_BATCH_DESCRIPTION', models.CharField(blank=True, default='', max_length=100)),
                ('V_CREATED_BY', models.CharField(max_length=20)),
                ('V_CREATED_DATE', models.DateTimeField(auto_now_add=True)),
                ('V_LAST_MODIFIED_DATE', models.DateTimeField(auto_now_add=True)),
                ('V_LAST_MODIFIED_BY', models.CharField(max_length=20)),
                ('V_BATCH_TYPE', models.CharField(blank=True, default='', max_length=5)),
                ('V_SRC_FRAMEWORK', models.CharField(blank=True, default='', max_length=5)),
                ('V_DSN_NAME', models.CharField(blank=True, default='', max_length=50)),
                ('V_IS_SEQUENTIAL', models.CharField(blank=True, default='', max_length=5)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('V_BATCH_ID',),
            },
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_BATCH_ID', models.IntegerField(default=0)),
                ('V_TASK_ID', models.CharField(blank=True, default='', max_length=20)),
                ('I_PARAMETER_ORDER', models.IntegerField(default=0)),
                ('V_PARAMETER_NAME', models.CharField(blank=True, default='', max_length=400)),
                ('V_PARAMETER_VALUE', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'ordering': ('V_BATCH_ID', 'V_TASK_ID', 'I_PARAMETER_ORDER'),
            },
        ),
    ]
