# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='V_CREATED_BY',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='V_LAST_MODIFIED_BY',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
