# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FsiMAllocationRule',
            fields=[
                ('allocation_sys_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('allocation_type_cd', models.IntegerField(blank=True, null=True)),
                ('source_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('factor_operator_type', models.CharField(blank=True, max_length=1, null=True)),
                ('factor_operator_accr_basis', models.CharField(blank=True, max_length=1, null=True)),
                ('factor_operator_constant', models.CharField(blank=True, max_length=1, null=True)),
                ('factor_constant', models.FloatField(blank=True, null=True)),
                ('factor_accrual_basis_cd', models.IntegerField(blank=True, null=True)),
                ('allocation_operator', models.CharField(blank=True, max_length=1, null=True)),
                ('driver_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('assignment_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('no_offset_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('offset_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('output_option_cd', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'fsi_m_allocation_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsiMAllocDetails',
            fields=[
                ('alloc_element_sys_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alloc_element_type', models.CharField(max_length=1, primary_key=True)),
                ('lookup_table_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('table_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('source_constant', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('leaf_selection_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('table_name', models.CharField(blank=True, max_length=30, null=True)),
                ('column_type', models.CharField(blank=True, max_length=1, null=True)),
                ('column_name', models.CharField(blank=True, max_length=30, null=True)),
                ('formula_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('filter_type', models.CharField(blank=True, max_length=1, null=True)),
                ('filter_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('aggregate_to_ledger', models.CharField(blank=True, max_length=1, null=True)),
                ('balance_type_cd', models.IntegerField(blank=True, null=True)),
                ('allocation_type_cd', models.IntegerField(blank=True, null=True)),
                ('percent_driver_type', models.CharField(blank=True, max_length=1, null=True)),
                ('scenario_cd', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fsi_m_alloc_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FsiMAllocLeafSelection',
            fields=[
                ('leaf_selection_sys_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('leaf_selection_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('leaf_num_id', models.IntegerField(primary_key=True)),
                ('leaf_node', models.BigIntegerField(blank=True, null=True)),
                ('hierarchy_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('hierarchy_level', models.IntegerField(blank=True, null=True)),
                ('tree_filter_sys_id', models.BigIntegerField(blank=True, null=True)),
                ('alloc_dim_subtype_cd', models.IntegerField(blank=True, null=True)),
                ('dimension_currency_value', models.CharField(blank=True, max_length=30, null=True)),
                ('leaf_code', models.CharField(blank=True, max_length=30, null=True)),
                ('hier_type', models.CharField(blank=True, max_length=2, null=True)),
                ('hier_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'fsi_m_alloc_leaf_selection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='profitability.Album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('album', 'order')]),
        ),
    ]
