# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0002_auto_20170606_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='id',
            new_name='id_album',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album',
            new_name='album_id',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('album_id', 'order')]),
        ),
    ]
