# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0003_auto_20170606_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='id_album',
            new_name='album_id',
        ),
    ]
