# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0004_auto_20170606_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('album', 'order')]),
        ),
    ]
