# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0005_auto_20170606_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100, primary_key=True),
        ),
    ]
