# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0007_auto_20170607_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100),
        ),
    ]
