# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0009_auto_20170607_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user2',
        ),
    ]
