# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profitability', '0012_auto_20170608_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
