# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_name', models.CharField(max_length=100)),
                ('member_b_table_name', models.CharField(max_length=30)),
                ('member_tl_table_name', models.CharField(max_length=30)),
                ('member_col', models.CharField(max_length=30)),
                ('member_display_code_col', models.CharField(max_length=30)),
                ('member_name_col', models.CharField(max_length=30)),
                ('member_description_col', models.CharField(max_length=30)),
                ('hierarchy_table_name', models.CharField(max_length=30)),
                ('attribute_table_name', models.CharField(max_length=30)),
                ('member_code_column', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'DIMENSIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_code', models.IntegerField(default=0)),
                ('id_alfa', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'DIM_ORG_UNIT_ATTR',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_code', models.IntegerField(default=0)),
                ('id_alfa', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('if_lead', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'DIM_ORG_UNIT_B',
            },
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
