# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170426_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={},
        ),
    ]
