# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170426_1712'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dimension',
            table=None,
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
