# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170426_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
