# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170525_1617'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='DIM_ORG_UNIT_ATTR',
        ),
        migrations.AlterModelTable(
            name='dimension',
            table='DIMENSIONS',
        ),
        migrations.AlterModelTable(
            name='member',
            table='DIM_ORG_UNIT_B',
        ),
    ]
