# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20170525_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='DIM_PRODUCT_ATTR',
        ),
        migrations.AlterModelTable(
            name='member',
            table='DIM_PRODUCT_B',
        ),
    ]
